### ISSUE TITLE
[feat]对引用字典及组词的支持

### ISSUE THREAD

**Issue by Newdea** [shitlime/RimeSpellTool#1]
感谢作者，很好用的工具，希望能再支持下引用字典及组词。

```
import_tables:
  # - xxx.extended

encoder:
  exclude_patterns:
    - '^z.*$'
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCb"
    - length_in_range: [4, 90]
      formula: "AaBaCaZa"

```
